// Puente seguro renderer <-> main. El renderer solo ve estas funciones; nunca las claves (salvo export explícito).
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  status: () => ipcRenderer.invoke('vault:status'),
  // Modo visor: solo lectura, no exige boveda abierta y no puede firmar.
  visorLista: () => ipcRenderer.invoke('visor:lista'),
  visorAnadir: (a) => ipcRenderer.invoke('visor:anadir', a),
  visorQuitar: (a) => ipcRenderer.invoke('visor:quitar', a),
  visorRenombrar: (a) => ipcRenderer.invoke('visor:renombrar', a),
  visorCuenta: (a) => ipcRenderer.invoke('visor:cuenta', a),
  setup: (passphrase, kind, net) => ipcRenderer.invoke('vault:setup', { passphrase, kind, net }),
  unlock: (passphrase) => ipcRenderer.invoke('vault:unlock', { passphrase }),
  lock: () => ipcRenderer.invoke('vault:lock'),
  balances: () => ipcRenderer.invoke('balances'),
  // NFT (solo lectura de momento): el main sale a la red y devuelve las imágenes
  // ya como data URL, para no abrir la CSP del renderer
  nftList: (a) => ipcRenderer.invoke('nft:list', a),
  nftAdd: (a) => ipcRenderer.invoke('nft:add', a),
  nftRemove: (a) => ipcRenderer.invoke('nft:remove', a),
  kdaValidar: (c) => ipcRenderer.invoke('kda:validar', c),
  evmSwapCotizar: (a) => ipcRenderer.invoke('evmswap:cotizar', a),
  evmSwapEnviar: (a) => ipcRenderer.invoke('evmswap:enviar', a),
  onEvmSwapProgress: (cb) => ipcRenderer.on('evmswap:progress', (_e, m) => cb(m)),
  dcaEstado: (a) => ipcRenderer.invoke('dca:estado', a),
  dcaPanel: () => ipcRenderer.invoke('dca:panel'),
  dcaCrear: (a) => ipcRenderer.invoke('dca:crear', a),
  dcaRecargar: (a) => ipcRenderer.invoke('dca:recargar', a),
  dcaAccion: (a) => ipcRenderer.invoke('dca:accion', a),
  nftComprobar: (a) => ipcRenderer.invoke('nft:comprobar', a),
  nftEnviar: (a) => ipcRenderer.invoke('nft:enviar', a),
  sendKda: (passphrase, walletId, kdaNet, chain, to, amount) => ipcRenderer.invoke('send:kda', { passphrase, walletId, kdaNet, chain, to, amount }),
  sendKdaToken: (passphrase, walletId, symbol, to, amount) => ipcRenderer.invoke('send:kdatoken', { passphrase, walletId, symbol, to, amount }),
  sendEvm: (passphrase, walletId, network, token, to, amount) => ipcRenderer.invoke('send:evm', { passphrase, walletId, network, token, to, amount }),
  devnetFaucet: (walletId) => ipcRenderer.invoke('devnet:faucet', { walletId }),
  sendKdaXchain: (passphrase, walletId, kdaNet, sourceChain, targetChain, to, amount) => ipcRenderer.invoke('send:kda-xchain', { passphrase, walletId, kdaNet, sourceChain, targetChain, to, amount }),
  sendKdaSmart: (passphrase, walletId, kdaNet, targetChain, to, amount) => ipcRenderer.invoke('send:kda-smart', { passphrase, walletId, kdaNet, targetChain, to, amount }),
  onXchainProgress: (cb) => ipcRenderer.on('xchain:progress', (_e, m) => cb(m)),
  // multi-wallet
  walletList: () => ipcRenderer.invoke('wallet:list'),
  walletShown: (id, shown) => ipcRenderer.invoke('wallet:shown', { id, shown }),
  walletRemove: (id) => ipcRenderer.invoke('wallet:remove', { id }),
  renameWallet: (id, label) => ipcRenderer.invoke('wallet:rename', { id, label }),
  createWallet: (label, kind, net) => ipcRenderer.invoke('wallet:create', { label, kind, net }),
  importMnemonic: (label, mnemonic, kind, net, index, method) => ipcRenderer.invoke('wallet:import-mnemonic', { label, mnemonic, kind, net, index, method }),
  seedAccounts: (mnemonic, kind, net, start, count) => ipcRenderer.invoke('seed:accounts', { mnemonic, kind, net, start, count }),
  seedFind: (mnemonic, kind, net, target, maxIndex) => ipcRenderer.invoke('seed:find', { mnemonic, kind, net, target, maxIndex }),
  importPrivkey: (label, kind, net, priv) => ipcRenderer.invoke('wallet:import-privkey', { label, kind, net, priv }),
  ledgerPeek: (kind, index, verify) => ipcRenderer.invoke('ledger:peek', { kind, index, verify }),
  ledgerImport: (label, kind, net, index) => ipcRenderer.invoke('ledger:import', { label, kind, net, index }),
  exportKey: (passphrase, walletId, chain) => ipcRenderer.invoke('wallet:export', { passphrase, walletId, chain }),
  bridgeConfig: () => ipcRenderer.invoke('bridge:config'),
  bridgeTokens: (walletId, dir) => ipcRenderer.invoke('bridge:tokens', { walletId, dir }),
  bridgeDryRun: (dir, fromWalletId, symbol, recipient, amount) => ipcRenderer.invoke('bridge:dryrun', { dir, fromWalletId, symbol, recipient, amount }),
  bridgeSend: (dir, passphrase, fromWalletId, symbol, recipient, amount) => ipcRenderer.invoke('bridge:send', { dir, passphrase, fromWalletId, symbol, recipient, amount }),
  onBridgeStep: (cb) => { const h = (_e, d) => cb(d); ipcRenderer.on('bridge:step', h); return () => ipcRenderer.removeListener('bridge:step', h); },
  pingActivity: () => ipcRenderer.send('activity:ping'),
  onLocked: (cb) => { ipcRenderer.on('locked', () => cb()); },
  swapQuote: (dir, amount) => ipcRenderer.invoke('swap:quote', { dir, amount }),
  swapExec: (passphrase, walletId, dir, amount, slippage) => ipcRenderer.invoke('swap:exec', { passphrase, walletId, dir, amount, slippage }),
  ethswapQuote: (dir, amount) => ipcRenderer.invoke('ethswap:quote', { dir, amount }),
  ethswapExec: (passphrase, walletId, dir, amount, minOut) => ipcRenderer.invoke('ethswap:exec', { passphrase, walletId, dir, amount, minOut }),
  history: (walletId) => ipcRenderer.invoke('history:list', { walletId }),
  txInfo: (requestKey, chain, redKey) => ipcRenderer.invoke('tx:info', { requestKey, chain, redKey }),
  qr: (text) => ipcRenderer.invoke('qr', text),
  exportHistory: (rows, filename) => ipcRenderer.invoke('history:export', { rows, filename }),
  prices: () => ipcRenderer.invoke('prices'),
  vaultBackup: () => ipcRenderer.invoke('vault:backup'),
  vaultRestore: (passphrase) => ipcRenderer.invoke('vault:restore', { passphrase }),
  backupExport: (password) => ipcRenderer.invoke('backup:export', { password }),
  backupImport: (password) => ipcRenderer.invoke('backup:import', { password }),
  getConfig: () => ipcRenderer.invoke('config:get'),
  setConfig: (c) => ipcRenderer.invoke('config:set', c),
  appInfo: () => ipcRenderer.invoke('app:info'),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateApply: () => ipcRenderer.invoke('update:apply'),
  openExternal: (url) => ipcRenderer.invoke('open:external', url)
});
